"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-30 17:57:13.547441
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import jat.db.types

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agencies",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.Column("updated_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agencies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agencies_name"), ["name"], unique=False)

    op.create_table(
        "attachments",
        sa.Column("entity_type", sa.String(length=20), nullable=True),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("original_name", sa.String(length=300), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("created_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_attachments_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_attachments_sha256"), ["sha256"], unique=False)

    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.Column("updated_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_companies_name"), ["name"], unique=False)

    op.create_table(
        "documents",
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.Column("updated_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "links",
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("created_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("links", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_links_entity_id"), ["entity_id"], unique=False)

    op.create_table(
        "note_index",
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("links", sa.JSON(), nullable=False),
        sa.Column("created_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.Column("updated_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.Column("mtime_ns", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_table(
        "contacts",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("agency_id", sa.String(length=36), nullable=True),
        sa.Column("company_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.Column("updated_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.ForeignKeyConstraint(["agency_id"], ["agencies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contacts_agency_id"), ["agency_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_contacts_company_id"), ["company_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_contacts_name"), ["name"], unique=False)

    op.create_table(
        "document_versions",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("attachment_id", sa.String(length=36), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["attachment_id"], ["attachments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_document_versions_document_id"), ["document_id"], unique=False)

    op.create_table(
        "roles",
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("work_mode", sa.String(length=20), nullable=True),
        sa.Column("employment_type", sa.String(length=20), nullable=True),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("day_rate", sa.Integer(), nullable=True),
        sa.Column("ir35", sa.String(length=20), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.Column("updated_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_roles_company_id"), ["company_id"], unique=False)

    op.create_table(
        "applications",
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("route", sa.String(length=20), nullable=False),
        sa.Column("agency_id", sa.String(length=36), nullable=True),
        sa.Column("recruiter_id", sa.String(length=36), nullable=True),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("applied_on", jat.db.types.ISODate(length=10), nullable=True),
        sa.Column("follow_up_on", jat.db.types.ISODate(length=10), nullable=True),
        sa.Column("snoozed_until", jat.db.types.ISODate(length=10), nullable=True),
        sa.Column("last_activity_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.Column("updated_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.ForeignKeyConstraint(["agency_id"], ["agencies.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["recruiter_id"], ["contacts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_applications_agency_id"), ["agency_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_applications_last_activity_at"), ["last_activity_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_applications_recruiter_id"), ["recruiter_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_applications_role_id"), ["role_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_applications_stage"), ["stage"], unique=False)

    op.create_table(
        "contact_details",
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("value", sa.String(length=500), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contact_details", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contact_details_contact_id"), ["contact_id"], unique=False)

    op.create_table(
        "application_contacts",
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("relation", sa.String(length=30), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("application_id", "contact_id", "relation"),
    )
    with op.batch_alter_table("application_contacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_application_contacts_application_id"), ["application_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_application_contacts_contact_id"), ["contact_id"], unique=False)

    op.create_table(
        "application_documents",
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("document_version_id", sa.String(length=36), nullable=False),
        sa.Column("sent_on", jat.db.types.ISODate(length=10), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_version_id"], ["document_versions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("application_id", "document_version_id"),
    )
    with op.batch_alter_table("application_documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_application_documents_application_id"), ["application_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_application_documents_document_version_id"), ["document_version_id"], unique=False
        )

    op.create_table(
        "events",
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("occurred_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.Column("from_stage", sa.String(length=40), nullable=True),
        sa.Column("to_stage", sa.String(length=40), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_application_id"), ["application_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_occurred_at"), ["occurred_at"], unique=False)

    op.create_table(
        "interviews",
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("starts_at", jat.db.types.UTCDateTime(length=32), nullable=True),
        sa.Column("ends_at", jat.db.types.UTCDateTime(length=32), nullable=True),
        sa.Column("deadline_at", jat.db.types.UTCDateTime(length=32), nullable=True),
        sa.Column("format", sa.String(length=20), nullable=True),
        sa.Column("location", sa.String(length=300), nullable=True),
        sa.Column("meeting_url", sa.String(length=1000), nullable=True),
        sa.Column("prep", sa.Text(), nullable=True),
        sa.Column("debrief", sa.Text(), nullable=True),
        sa.Column("questions", sa.Text(), nullable=True),
        sa.Column("task_instructions", sa.Text(), nullable=True),
        sa.Column("task_repo_url", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.Column("updated_at", jat.db.types.UTCDateTime(length=32), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("interviews", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_interviews_application_id"), ["application_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_interviews_deadline_at"), ["deadline_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_interviews_starts_at"), ["starts_at"], unique=False)

    op.create_table(
        "interview_contacts",
        sa.Column("interview_id", sa.String(length=36), nullable=False),
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["interview_id"], ["interviews.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("interview_id", "contact_id"),
    )
    with op.batch_alter_table("interview_contacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_interview_contacts_contact_id"), ["contact_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_interview_contacts_interview_id"), ["interview_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interview_contacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interview_contacts_interview_id"))
        batch_op.drop_index(batch_op.f("ix_interview_contacts_contact_id"))

    op.drop_table("interview_contacts")
    with op.batch_alter_table("interviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interviews_starts_at"))
        batch_op.drop_index(batch_op.f("ix_interviews_deadline_at"))
        batch_op.drop_index(batch_op.f("ix_interviews_application_id"))

    op.drop_table("interviews")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_events_application_id"))

    op.drop_table("events")
    with op.batch_alter_table("application_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_application_documents_document_version_id"))
        batch_op.drop_index(batch_op.f("ix_application_documents_application_id"))

    op.drop_table("application_documents")
    with op.batch_alter_table("application_contacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_application_contacts_contact_id"))
        batch_op.drop_index(batch_op.f("ix_application_contacts_application_id"))

    op.drop_table("application_contacts")
    with op.batch_alter_table("contact_details", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contact_details_contact_id"))

    op.drop_table("contact_details")
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_applications_stage"))
        batch_op.drop_index(batch_op.f("ix_applications_role_id"))
        batch_op.drop_index(batch_op.f("ix_applications_recruiter_id"))
        batch_op.drop_index(batch_op.f("ix_applications_last_activity_at"))
        batch_op.drop_index(batch_op.f("ix_applications_agency_id"))

    op.drop_table("applications")
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roles_company_id"))

    op.drop_table("roles")
    with op.batch_alter_table("document_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_versions_document_id"))

    op.drop_table("document_versions")
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contacts_name"))
        batch_op.drop_index(batch_op.f("ix_contacts_company_id"))
        batch_op.drop_index(batch_op.f("ix_contacts_agency_id"))

    op.drop_table("contacts")
    op.drop_table("note_index")
    with op.batch_alter_table("links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_links_entity_id"))

    op.drop_table("links")
    op.drop_table("documents")
    with op.batch_alter_table("companies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_companies_name"))

    op.drop_table("companies")
    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attachments_sha256"))
        batch_op.drop_index(batch_op.f("ix_attachments_entity_id"))

    op.drop_table("attachments")
    with op.batch_alter_table("agencies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agencies_name"))

    op.drop_table("agencies")
    # ### end Alembic commands ###
