/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/agencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_v1_agencies_get"];
        put?: never;
        /** Create Item */
        post: operations["create_item_api_v1_agencies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agencies/{agency_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agency Summary */
        get: operations["agency_summary_api_v1_agencies__agency_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agencies/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item_api_v1_agencies__item_id__get"];
        put?: never;
        post?: never;
        /** Delete Item */
        delete: operations["delete_item_api_v1_agencies__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["update_item_api_v1_agencies__item_id__patch"];
        trace?: never;
    };
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_api_v1_applications_get"];
        put?: never;
        /** Create App */
        post: operations["create_app__api_v1_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find Duplicates
         * @description Existing applications that look like the same job, to warn before applying twice.
         *
         *     Give the company by id, or by name ("Contoso Ltd" matches "Contoso").
         */
        get: operations["find_duplicates_api_v1_applications_duplicates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/quick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Quick Create
         * @description One transaction: reuse or create the company, role, agency and recruiter, then the application.
         *
         *     If anything fails, nothing is saved, so a retry never leaves duplicates behind.
         */
        post: operations["quick_create_api_v1_applications_quick_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{app_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App */
        get: operations["get_app_api_v1_applications__app_id__get"];
        put?: never;
        post?: never;
        /** Delete App */
        delete: operations["delete_app_api_v1_applications__app_id__delete"];
        options?: never;
        head?: never;
        /** Update App */
        patch: operations["update_app_api_v1_applications__app_id__patch"];
        trace?: never;
    };
    "/api/v1/applications/{app_id}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Activity */
        post: operations["add_activity_api_v1_applications__app_id__activities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{app_id}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Contact */
        post: operations["link_contact_api_v1_applications__app_id__contacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{app_id}/contacts/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unlink Contact */
        delete: operations["unlink_contact_api_v1_applications__app_id__contacts__link_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{app_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** App Events */
        get: operations["app_events_api_v1_applications__app_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{app_id}/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Interview */
        post: operations["create_interview_api_v1_applications__app_id__interviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{app_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move App */
        post: operations["move_app_api_v1_applications__app_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{app_id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo App */
        post: operations["undo_app_api_v1_applications__app_id__undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backup Status */
        get: operations["backup_status_api_v1_backup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backup/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push */
        post: operations["push_api_v1_backup_push_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backup/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Snapshot */
        post: operations["snapshot_api_v1_backup_snapshot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_v1_companies_get"];
        put?: never;
        /** Create Item */
        post: operations["create_item_api_v1_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{company_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company Summary */
        get: operations["company_summary_api_v1_companies__company_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/companies/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item_api_v1_companies__item_id__get"];
        put?: never;
        post?: never;
        /** Delete Item */
        delete: operations["delete_item_api_v1_companies__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["update_item_api_v1_companies__item_id__patch"];
        trace?: never;
    };
    "/api/v1/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contacts */
        get: operations["list_contacts_api_v1_contacts_get"];
        put?: never;
        /** Create Contact */
        post: operations["create_contact_api_v1_contacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contacts/{contact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contact */
        get: operations["get_contact_api_v1_contacts__contact_id__get"];
        put?: never;
        post?: never;
        /** Delete Contact */
        delete: operations["delete_contact_api_v1_contacts__contact_id__delete"];
        options?: never;
        head?: never;
        /** Update Contact */
        patch: operations["update_contact_api_v1_contacts__contact_id__patch"];
        trace?: never;
    };
    "/api/v1/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Interviews
         * @description Interviews, soonest first.
         *
         *     `upcoming` keeps scheduled ones from `since` on, plus those with no date yet. Pass the start
         *     of your local day as `since`; it defaults to the start of today in UTC.
         */
        get: operations["list_interviews_api_v1_interviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interviews/titles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Interview Titles
         * @description Round descriptions used before, most used first: suggestions for the next one.
         */
        get: operations["interview_titles_api_v1_interviews_titles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/interviews/{interview_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Interview */
        get: operations["get_interview_api_v1_interviews__interview_id__get"];
        put?: never;
        post?: never;
        /** Delete Interview */
        delete: operations["delete_interview_api_v1_interviews__interview_id__delete"];
        options?: never;
        head?: never;
        /** Update Interview */
        patch: operations["update_interview_api_v1_interviews__interview_id__patch"];
        trace?: never;
    };
    "/api/v1/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Links */
        get: operations["list_links_api_v1_links_get"];
        put?: never;
        /** Create Link */
        post: operations["create_link_api_v1_links_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/links/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Link */
        delete: operations["delete_link_api_v1_links__link_id__delete"];
        options?: never;
        head?: never;
        /** Update Link */
        patch: operations["update_link_api_v1_links__link_id__patch"];
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_api_v1_roles_get"];
        put?: never;
        /** Create Item */
        post: operations["create_item_api_v1_roles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item_api_v1_roles__item_id__get"];
        put?: never;
        post?: never;
        /** Delete Item */
        delete: operations["delete_item_api_v1_roles__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["update_item_api_v1_roles__item_id__patch"];
        trace?: never;
    };
    "/api/v1/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow Config */
        get: operations["get_workflow_config_api_v1_workflow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityIn */
        ActivityIn: {
            /**
             * Data
             * @default {}
             */
            data: {
                [key: string]: unknown;
            };
            /**
             * Kind
             * @enum {string}
             */
            kind: "call" | "email" | "message" | "note" | "file" | "interview" | "manual";
            /** Occurred At */
            occurred_at?: string | null;
            /** Summary */
            summary?: string | null;
        };
        /** AgencyIn */
        AgencyIn: {
            /** Name */
            name: string;
            /** Website */
            website?: string | null;
        };
        /** AgencyOut */
        AgencyOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Website */
            website: string | null;
        };
        /** AgencyPatch */
        AgencyPatch: {
            /** Name */
            name?: string | null;
            /** Website */
            website?: string | null;
        };
        /** AgencySummary */
        AgencySummary: {
            agency: components["schemas"]["AgencyOut"];
            /** Applications */
            applications: components["schemas"]["ApplicationRow"][];
            /** Recruiters */
            recruiters: components["schemas"]["ContactOut"][];
        };
        /** ApplicationContactIn */
        ApplicationContactIn: {
            /** Contact Id */
            contact_id: string;
            /**
             * Relation
             * @enum {string}
             */
            relation: "recruiter" | "hiring_manager" | "interviewer" | "referrer" | "other";
        };
        /** ApplicationContactOut */
        ApplicationContactOut: {
            /** Application Id */
            application_id: string;
            /** Contact Id */
            contact_id: string;
            /** Id */
            id: string;
            /** Relation */
            relation: string;
        };
        /** ApplicationDetail */
        ApplicationDetail: {
            /** Agency Id */
            agency_id: string | null;
            /** Agency Name */
            agency_name: string | null;
            /** Allowed Next */
            allowed_next: string[];
            /** Applied On */
            applied_on: string | null;
            /** Archived */
            archived: boolean;
            /** Can Undo */
            can_undo: boolean;
            /** Company Id */
            company_id: string;
            /** Company Name */
            company_name: string;
            /** Contacts */
            contacts: components["schemas"]["ApplicationContactOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            current_round?: components["schemas"]["RoundSummary"] | null;
            /** Days Since Activity */
            days_since_activity: number;
            /** Duplicates */
            duplicates: components["schemas"]["DuplicateOut"][];
            /** Events */
            events: components["schemas"]["EventOut"][];
            /** Follow Up On */
            follow_up_on: string | null;
            /** Id */
            id: string;
            /**
             * Last Activity At
             * Format: date-time
             */
            last_activity_at: string;
            /** Recruiter Id */
            recruiter_id: string | null;
            /** Recruiter Name */
            recruiter_name: string | null;
            /** Role Id */
            role_id: string;
            /** Role Title */
            role_title: string;
            /** Route */
            route: string;
            /** Snoozed Until */
            snoozed_until: string | null;
            /** Stage */
            stage: string;
            /** Stage Kind */
            stage_kind: string;
            /** Stage Name */
            stage_name: string;
            /** Stale */
            stale: boolean;
            /** Suggested Next */
            suggested_next: string[];
            /** Tags */
            tags: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ApplicationIn */
        ApplicationIn: {
            /** Agency Id */
            agency_id?: string | null;
            /** Applied On */
            applied_on?: string | null;
            /** Follow Up On */
            follow_up_on?: string | null;
            /** Recruiter Id */
            recruiter_id?: string | null;
            /** Role Id */
            role_id: string;
            /**
             * Route
             * @default direct
             * @enum {string}
             */
            route: "direct" | "agency" | "referral";
            /** Stage */
            stage?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
        };
        /**
         * ApplicationPatch
         * @description Stage is changed with POST /applications/{id}/move, not here.
         */
        ApplicationPatch: {
            /** Agency Id */
            agency_id?: string | null;
            /** Applied On */
            applied_on?: string | null;
            /** Archived */
            archived?: boolean | null;
            /** Follow Up On */
            follow_up_on?: string | null;
            /** Recruiter Id */
            recruiter_id?: string | null;
            /** Role Id */
            role_id?: string | null;
            /** Route */
            route?: ("direct" | "agency" | "referral") | null;
            /** Snoozed Until */
            snoozed_until?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /**
         * ApplicationRow
         * @description An application with the names the list and board need.
         */
        ApplicationRow: {
            /** Agency Id */
            agency_id: string | null;
            /** Agency Name */
            agency_name: string | null;
            /** Applied On */
            applied_on: string | null;
            /** Archived */
            archived: boolean;
            /** Company Id */
            company_id: string;
            /** Company Name */
            company_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            current_round?: components["schemas"]["RoundSummary"] | null;
            /** Days Since Activity */
            days_since_activity: number;
            /** Follow Up On */
            follow_up_on: string | null;
            /** Id */
            id: string;
            /**
             * Last Activity At
             * Format: date-time
             */
            last_activity_at: string;
            /** Recruiter Id */
            recruiter_id: string | null;
            /** Recruiter Name */
            recruiter_name: string | null;
            /** Role Id */
            role_id: string;
            /** Role Title */
            role_title: string;
            /** Route */
            route: string;
            /** Snoozed Until */
            snoozed_until: string | null;
            /** Stage */
            stage: string;
            /** Stage Kind */
            stage_kind: string;
            /** Stage Name */
            stage_name: string;
            /** Stale */
            stale: boolean;
            /** Tags */
            tags: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** BackupStatus */
        BackupStatus: {
            /** Debounce Seconds */
            debounce_seconds: number;
            /** Dirty */
            dirty: boolean;
            /** Enabled */
            enabled: boolean;
            /** Has Remote */
            has_remote: boolean;
            /** Last Commit */
            last_commit: string | null;
            /** Last Error */
            last_error: string | null;
            /** Last Push At */
            last_push_at: string | null;
            /** Last Snapshot At */
            last_snapshot_at: string | null;
            /** Unpushed Commits */
            unpushed_commits: number | null;
        };
        /** CompanyIn */
        CompanyIn: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /** Website */
            website?: string | null;
        };
        /** CompanyOut */
        CompanyOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Website */
            website: string | null;
        };
        /** CompanyPatch */
        CompanyPatch: {
            /** Description */
            description?: string | null;
            /** Name */
            name?: string | null;
            /** Website */
            website?: string | null;
        };
        /** CompanySummary */
        CompanySummary: {
            /** Applications */
            applications: components["schemas"]["ApplicationRow"][];
            company: components["schemas"]["CompanyOut"];
            /** Contacts */
            contacts: components["schemas"]["ContactOut"][];
            /** Roles */
            roles: components["schemas"]["RoleOut"][];
        };
        /** ContactDetailIn */
        ContactDetailIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "email" | "phone" | "linkedin" | "url" | "other";
            /** Label */
            label?: string | null;
            /** Value */
            value: string;
        };
        /** ContactDetailOut */
        ContactDetailOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string | null;
            /** Position */
            position: number;
            /** Value */
            value: string;
        };
        /** ContactIn */
        ContactIn: {
            /** Agency Id */
            agency_id?: string | null;
            /** Company Id */
            company_id?: string | null;
            /**
             * Details
             * @default []
             */
            details: components["schemas"]["ContactDetailIn"][];
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
        };
        /** ContactOut */
        ContactOut: {
            /** Agency Id */
            agency_id: string | null;
            /** Company Id */
            company_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Details
             * @default []
             */
            details: components["schemas"]["ContactDetailOut"][];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Title */
            title: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ContactPatch */
        ContactPatch: {
            /** Agency Id */
            agency_id?: string | null;
            /** Company Id */
            company_id?: string | null;
            /** Details */
            details?: components["schemas"]["ContactDetailIn"][] | null;
            /** Name */
            name?: string | null;
            /** Title */
            title?: string | null;
        };
        /**
         * DuplicateOut
         * @description Another application that looks like the same job: same company, same or similar title.
         */
        DuplicateOut: {
            /** Agency Id */
            agency_id: string | null;
            /** Agency Name */
            agency_name: string | null;
            /** Applied On */
            applied_on: string | null;
            /** Archived */
            archived: boolean;
            /** Company Id */
            company_id: string;
            /** Company Name */
            company_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            current_round?: components["schemas"]["RoundSummary"] | null;
            /** Days Since Activity */
            days_since_activity: number;
            /** Follow Up On */
            follow_up_on: string | null;
            /** Id */
            id: string;
            /**
             * Last Activity At
             * Format: date-time
             */
            last_activity_at: string;
            /**
             * Match
             * @enum {string}
             */
            match: "same_role" | "similar_title";
            /** Recruiter Id */
            recruiter_id: string | null;
            /** Recruiter Name */
            recruiter_name: string | null;
            /** Role Id */
            role_id: string;
            /** Role Title */
            role_title: string;
            /** Route */
            route: string;
            /** Snoozed Until */
            snoozed_until: string | null;
            /** Stage */
            stage: string;
            /** Stage Kind */
            stage_kind: string;
            /** Stage Name */
            stage_name: string;
            /** Stale */
            stale: boolean;
            /** Tags */
            tags: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EventOut */
        EventOut: {
            /** Application Id */
            application_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** From Stage */
            from_stage: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Summary */
            summary: string | null;
            /** To Stage */
            to_stage: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InterviewIn
         * @description An interview round. Leave `round` out to make it the next round for the application.
         */
        InterviewIn: {
            /** Deadline At */
            deadline_at?: string | null;
            /** Debrief */
            debrief?: string | null;
            /** Ends At */
            ends_at?: string | null;
            /** Format */
            format?: ("video" | "phone" | "onsite" | "take_home") | null;
            /**
             * Interviewer Ids
             * @default []
             */
            interviewer_ids: string[];
            /**
             * Kind
             * @default technical
             * @enum {string}
             */
            kind: "screen" | "hiring_manager" | "technical" | "coding_task" | "system_design" | "pairing" | "behavioural" | "onsite" | "final" | "other";
            /** Location */
            location?: string | null;
            /** Meeting Url */
            meeting_url?: string | null;
            /** Prep */
            prep?: string | null;
            /** Questions */
            questions?: string | null;
            /** Round */
            round?: number | null;
            /** Starts At */
            starts_at?: string | null;
            /**
             * Status
             * @default scheduled
             * @enum {string}
             */
            status: "scheduled" | "done" | "cancelled";
            /** Task Instructions */
            task_instructions?: string | null;
            /** Task Repo Url */
            task_repo_url?: string | null;
            /** Title */
            title?: string | null;
        };
        /** InterviewOut */
        InterviewOut: {
            /** Application Id */
            application_id: string;
            /** Company Name */
            company_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deadline At */
            deadline_at: string | null;
            /** Debrief */
            debrief: string | null;
            /** Ends At */
            ends_at: string | null;
            /** Format */
            format: string | null;
            /** Id */
            id: string;
            /** Interviewer Ids */
            interviewer_ids: string[];
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Location */
            location: string | null;
            /** Meeting Url */
            meeting_url: string | null;
            /** Prep */
            prep: string | null;
            /** Questions */
            questions: string | null;
            /** Role Title */
            role_title: string;
            /** Round */
            round: number | null;
            /** Starts At */
            starts_at: string | null;
            /** Status */
            status: string;
            /** Task Instructions */
            task_instructions: string | null;
            /** Task Repo Url */
            task_repo_url: string | null;
            /** Title */
            title: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** InterviewPatch */
        InterviewPatch: {
            /** Deadline At */
            deadline_at?: string | null;
            /** Debrief */
            debrief?: string | null;
            /** Ends At */
            ends_at?: string | null;
            /** Format */
            format?: ("video" | "phone" | "onsite" | "take_home") | null;
            /** Interviewer Ids */
            interviewer_ids?: string[] | null;
            /** Kind */
            kind?: ("screen" | "hiring_manager" | "technical" | "coding_task" | "system_design" | "pairing" | "behavioural" | "onsite" | "final" | "other") | null;
            /** Location */
            location?: string | null;
            /** Meeting Url */
            meeting_url?: string | null;
            /** Prep */
            prep?: string | null;
            /** Questions */
            questions?: string | null;
            /** Round */
            round?: number | null;
            /** Starts At */
            starts_at?: string | null;
            /** Status */
            status?: ("scheduled" | "done" | "cancelled") | null;
            /** Task Instructions */
            task_instructions?: string | null;
            /** Task Repo Url */
            task_repo_url?: string | null;
            /** Title */
            title?: string | null;
        };
        /**
         * LinkIn
         * @description An external link (a Google Doc, the job ad, a repo…) on something. Title defaults from the URL.
         */
        LinkIn: {
            /** Entity Id */
            entity_id: string;
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "application" | "company" | "role" | "agency" | "contact" | "interview";
            /** Title */
            title?: string | null;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
        /** LinkOut */
        LinkOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Title */
            title: string | null;
            /** Url */
            url: string;
        };
        /** LinkPatch */
        LinkPatch: {
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
        };
        /** MoveIn */
        MoveIn: {
            /** Note */
            note?: string | null;
            /** Occurred At */
            occurred_at?: string | null;
            /** To Stage */
            to_stage: string;
        };
        /** PushResult */
        PushResult: {
            /** Output */
            output: string;
            status: components["schemas"]["BackupStatus"];
        };
        /**
         * QuickApplicationIn
         * @description Create an application and, in the same transaction, anything it needs that doesn't exist yet.
         *
         *     Company, agency and recruiter can each be given by id or by name. A name that matches an
         *     existing record (case-insensitively) reuses it; otherwise a new one is created. A recruiter
         *     name is matched within the application's agency.
         */
        QuickApplicationIn: {
            /** Agency Id */
            agency_id?: string | null;
            /** Agency Name */
            agency_name?: string | null;
            /** Applied On */
            applied_on?: string | null;
            /** Company Id */
            company_id?: string | null;
            /** Company Name */
            company_name?: string | null;
            /** Recruiter Id */
            recruiter_id?: string | null;
            /** Recruiter Name */
            recruiter_name?: string | null;
            /** Role Title */
            role_title: string;
            /** Role Url */
            role_url?: string | null;
            /**
             * Route
             * @default direct
             * @enum {string}
             */
            route: "direct" | "agency" | "referral";
            /** Stage */
            stage?: string | null;
            /**
             * Tags
             * @default []
             */
            tags: string[];
        };
        /** RoleIn */
        RoleIn: {
            /** Company Id */
            company_id: string;
            /** Currency */
            currency?: string | null;
            /** Day Rate */
            day_rate?: number | null;
            /** Description */
            description?: string | null;
            /** Employment Type */
            employment_type?: ("permanent" | "contract" | "fixed_term") | null;
            /** Ir35 */
            ir35?: ("inside" | "outside" | "unknown") | null;
            /** Location */
            location?: string | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Min */
            salary_min?: number | null;
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
            /** Work Mode */
            work_mode?: ("remote" | "hybrid" | "office") | null;
        };
        /** RoleOut */
        RoleOut: {
            /** Company Id */
            company_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Currency */
            currency: string | null;
            /** Day Rate */
            day_rate: number | null;
            /** Description */
            description: string | null;
            /** Employment Type */
            employment_type: string | null;
            /** Id */
            id: string;
            /** Ir35 */
            ir35: string | null;
            /** Location */
            location: string | null;
            /** Salary Max */
            salary_max: number | null;
            /** Salary Min */
            salary_min: number | null;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Url */
            url: string | null;
            /** Work Mode */
            work_mode: string | null;
        };
        /** RolePatch */
        RolePatch: {
            /** Company Id */
            company_id?: string | null;
            /** Currency */
            currency?: string | null;
            /** Day Rate */
            day_rate?: number | null;
            /** Description */
            description?: string | null;
            /** Employment Type */
            employment_type?: ("permanent" | "contract" | "fixed_term") | null;
            /** Ir35 */
            ir35?: ("inside" | "outside" | "unknown") | null;
            /** Location */
            location?: string | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Min */
            salary_min?: number | null;
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
            /** Work Mode */
            work_mode?: ("remote" | "hybrid" | "office") | null;
        };
        /**
         * RoundSummary
         * @description The round an application is at, for the board and list: "Round 2 · System design test".
         */
        RoundSummary: {
            /** Deadline At */
            deadline_at: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Round */
            round: number | null;
            /** Starts At */
            starts_at: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
        };
        /** SnapshotResult */
        SnapshotResult: {
            /** Commit */
            commit: string | null;
            status: components["schemas"]["BackupStatus"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_items_api_v1_agencies_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgencyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_v1_agencies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgencyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgencyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agency_summary_api_v1_agencies__agency_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agency_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgencySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_v1_agencies__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgencyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_v1_agencies__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_api_v1_agencies__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgencyPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgencyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_api_v1_applications_get: {
        parameters: {
            query?: {
                stage?: string[] | null;
                route?: ("direct" | "agency" | "referral") | null;
                agency_id?: string | null;
                recruiter_id?: string | null;
                company_id?: string | null;
                tag?: string | null;
                archived?: boolean;
                stale?: boolean | null;
                min_inactive_days?: number | null;
                q?: string | null;
                sort?: "last_activity" | "-last_activity" | "created" | "-created" | "company" | "stage";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_app__api_v1_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_duplicates_api_v1_applications_duplicates_get: {
        parameters: {
            query: {
                role_title: string;
                company_id?: string | null;
                company_name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quick_create_api_v1_applications_quick_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuickApplicationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_api_v1_applications__app_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_app_api_v1_applications__app_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_app_api_v1_applications__app_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_activity_api_v1_applications__app_id__activities_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_contact_api_v1_applications__app_id__contacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationContactIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationContactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unlink_contact_api_v1_applications__app_id__contacts__link_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    app_events_api_v1_applications__app_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_interview_api_v1_applications__app_id__interviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_app_api_v1_applications__app_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_app_api_v1_applications__app_id__undo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backup_status_api_v1_backup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupStatus"];
                };
            };
        };
    };
    push_api_v1_backup_push_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushResult"];
                };
            };
        };
    };
    snapshot_api_v1_backup_snapshot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResult"];
                };
            };
        };
    };
    list_items_api_v1_companies_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_v1_companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_summary_api_v1_companies__company_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_v1_companies__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_v1_companies__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_api_v1_companies__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contacts_api_v1_contacts_get: {
        parameters: {
            query?: {
                q?: string | null;
                agency_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_contact_api_v1_contacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contact_api_v1_contacts__contact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_contact_api_v1_contacts__contact_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contact_api_v1_contacts__contact_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interviews_api_v1_interviews_get: {
        parameters: {
            query?: {
                application_id?: string | null;
                status?: ("scheduled" | "done" | "cancelled") | null;
                upcoming?: boolean;
                since?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interview_titles_api_v1_interviews_titles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_interview_api_v1_interviews__interview_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_interview_api_v1_interviews__interview_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_interview_api_v1_interviews__interview_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_links_api_v1_links_get: {
        parameters: {
            query: {
                entity_type: "application" | "company" | "role" | "agency" | "contact" | "interview";
                entity_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_link_api_v1_links_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_link_api_v1_links__link_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_link_api_v1_links__link_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_api_v1_roles_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_item_api_v1_roles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_item_api_v1_roles__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_v1_roles__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_item_api_v1_roles__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_config_api_v1_workflow_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
