"""Attachment files (PRD FR13; stack RFC §4).

Files live under files/YYYY/MM/<id>-<safe name> in the data directory, which is committed with
the snapshots, so they're readable without the app. SQLite records each one with its original
name, type, size and SHA-256. Paths are always generated by the app, and nothing outside
files/ (or behind a symlink) is ever read, written or deleted.
"""

from __future__ import annotations

import hashlib
import os
import re
import tempfile
import unicodedata
from dataclasses import dataclass
from pathlib import Path
from typing import BinaryIO

from ..db.types import new_id, utcnow

MAX_BYTES = 50 * 1024 * 1024  # a CV, a brief, a screenshot: not videos
_CHUNK = 1024 * 1024


class FileError(ValueError):
    pass


class TooLarge(FileError):
    pass


@dataclass
class Stored:
    id: str
    path: str  # relative to files/, forward slashes
    size: int
    sha256: str


def safe_name(name: str, limit: int = 100) -> str:
    """A file name that's safe on any OS and in git: ASCII, no paths, extension kept."""
    base = name.replace("\\", "/").rsplit("/", 1)[-1]
    base = unicodedata.normalize("NFKD", base).encode("ascii", "ignore").decode()
    stem, dot, ext = base.rpartition(".")
    if not dot:
        stem, ext = base, ""
    stem = re.sub(r"[^A-Za-z0-9._-]+", "-", stem).strip("-._")[:limit] or "file"
    ext = re.sub(r"[^A-Za-z0-9]+", "", ext)[:10].lower()
    return f"{stem}.{ext}" if ext else stem


class FileStore:
    def __init__(self, data_dir: Path, max_bytes: int = MAX_BYTES) -> None:
        self.root = (data_dir / "files").resolve()
        self.max_bytes = max_bytes

    def resolve(self, rel_path: str) -> Path:
        path = (self.root / rel_path).resolve()
        if not path.is_relative_to(self.root) or path == self.root:
            raise FileError(f"{rel_path} isn't under files/")
        if (self.root / rel_path).is_symlink():
            raise FileError(f"{rel_path} is a symlink")
        return path

    def save(self, stream: BinaryIO, original_name: str) -> Stored:
        """Stream an upload to disk, hashing as it goes. Nothing is left behind if it fails."""
        now = utcnow()
        file_id = new_id()
        rel = f"{now:%Y/%m}/{file_id}-{safe_name(original_name)}"
        dest = self.resolve(rel)
        dest.parent.mkdir(parents=True, exist_ok=True)
        digest = hashlib.sha256()
        size = 0
        fd, tmp = tempfile.mkstemp(dir=dest.parent, prefix=".tmp-")
        try:
            with os.fdopen(fd, "wb") as out:
                while chunk := stream.read(_CHUNK):
                    size += len(chunk)
                    if size > self.max_bytes:
                        raise TooLarge(f"files can be up to {self.max_bytes // (1024 * 1024)} MB")
                    digest.update(chunk)
                    out.write(chunk)
            os.replace(tmp, dest)
        except BaseException:
            Path(tmp).unlink(missing_ok=True)
            raise
        return Stored(id=file_id, path=rel, size=size, sha256=digest.hexdigest())

    def delete(self, rel_path: str) -> None:
        self.resolve(rel_path).unlink(missing_ok=True)
